### ISSUE TITLE
paper-input no longer shows carret in firefox when focused

### ISSUE THREAD

**Issue by markovuksanovic** [PolymerElements/paper-input#110]
https://elements.polymer-project.org/elements/paper-input?view=demo:demo/index.html&active=paper-input

**Comment by jacktech24** [comment]
neither in chrome

**Comment by juliomelo** [comment]
This is a known Firefox bug (see [bug 509684 on bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=509684)). But I couldn't reproduce this problem on Chrome 44.

The carret is hidden, but the input text is still functional. This bug is triggered by iron-control-state behavior that stop focus event propagation (line 78).

This [simple code below](http://jsfiddle.net/juliomelo/601h7pz6/1/) demonstrates this bug on Firefox:

```html
<div id="container"><input /></div>
```

```javascript
function onFocus(event) {
    event.stopPropagation();
}
    
document.getElementById("container").addEventListener("focus", onFocus, true);
```

**Comment by markovuksanovic** [comment]
If that's the case, that's just ridiculous. This bug was reported in 2009. That's like 7 years ago.

**Comment by juliomelo** [comment]
If you just remove that line `event.stopPropagation();` from `_focusBlurHandler` method of `IronControlState`, it will work (I have already tested).

As [focus](http://www.w3.org/TR/DOM-Level-3-Events/#event-type-focus) and [blur](http://www.w3.org/TR/DOM-Level-3-Events/#event-type-blur) events does not bubble, I think that line could be removed, although it still could be captured. As you sad, that bug is 7 yeas old and all Firefox browsers, since FF 3, will behave like this until they decide to fix it, so I suggest that Polymer should handle it.

**Comment by notwaldorf** [comment]
@juliomelo there's already a PR in flight to fix this: https://github.com/PolymerElements/iron-behaviors/pull/25. It has 2 related PRs, so we're working on merging them all.

Once they land, I'll check again if there's any other outstanding cursor problems

**Comment by notwaldorf** [comment]
I can no longer reproduce this, so I think the fix above worked. Please let me know if this comes back :)
