### ISSUE TITLE
Label misalignment issue for preset value in combination with prefix

### ISSUE THREAD

**Issue by dbruechner** [PolymerElements/paper-input#149]
If you have a preset value for a paper-input element and a prefix, the initial label alignment/position seems to be wrong:
```
<paper-input value="hugo" label="thisisthelabel">
     <div prefix>a_prefix</div>
</paper-input>
```

Screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/7567881/9354527/5b6ddcb6-4671-11e5-9670-090df60c1379.jpg)

**Comment by notwaldorf** [comment]
Argh, this is happening because we don't get notified when the `prefix` div is stamped, so the label doesn't know it has to shift over. We'll have to wait on https://github.com/Polymer/polymer/issues/1773 to land for this to be properly fixed.

@dbruechner the only workaround i can see is to maybe focus the input manually to re-compute the label's value?

**Comment by dbruechner** [comment]
Makes sense as a workaround. I will see if I can wait or I am going to it like this, cheers anyways.

**Comment by L-u-k-e** [comment]
@notwaldorf  I just tried implementing your workaround by putting code analogous to this:

    my_paper_input_element.$$('input').focus() 

in the `ready` callback of the custom element that contains the `paper-input` I'm trying to fix.

However, that doesn't seem to work. No error are logged to the console, but the issue persists. 

I can't just call `ready` on the paper-input itself, because it doesn't implement that method:  https://github.com/Polymer/paper-input/issues/188

Have you tried the workaround yourself. Do you have a concrete example? 
Thanks.
