### ISSUE TITLE
Big performance problem w/ auto-validate

### ISSUE THREAD

**Issue by robrez** [PolymerElements/paper-input#160]
I'm seeing auto-validate make chrome (44) completely non-responsive.

http://codepen.io/robrez/pen/yNmxRb

I started stepping into some pretty low-level stuff and thought the pros would do better at resolving this. My initial thought was, "ah! I'll debounce the validity check"..

```
    _handleValue: function(inputElement) {
      var value = inputElement[this._propertyForValue] || inputElement.value;

      if (this.autoValidate) {

        //my changes here ..

        var f = function() {
          this._debounceValidity(inputElement);
        }.bind(this);
        this.debounce('validity', f, 500);
      }
      ....
    },


    _debounceValidityCheck: function(inputElement) {
      var value = inputElement[this._propertyForValue] || inputElement.value;
      if (this.autoValidate) {
        var valid;
        if (inputElement.validate) {
          valid = inputElement.validate(value);
        } else {
          valid = inputElement.checkValidity();
        }

        var currInvalid = this.invalid;
        if(currInvalid === valid) {
          this.invalid = !valid;
          this.updateAddons({
            inputElement: inputElement,
            value: value,
            invalid: this.invalid
          });
        }
      }
    },

```

 but that doesn't really seem to help. There is something else going on that I can't quite figure out.

Of course, the issue can be mitigated by _not_ auto-validating and/or by optimizing the regex as much as possible.

Thanks

**Comment by notwaldorf** [comment]
@robrez Whoa, neat! Good find. 😊 I'll take a look.

**Comment by notwaldorf** [comment]
@robrez I haven't looked into this yet -- did you manage to find out anything more?

**Comment by robrez** [comment]
Sorry, I haven't

**Comment by bicknellr** [comment]
@robrez This seems to be an issue with your regular expression. :/ If you run this:
```javascript
var start = performance.now();
/^[a-zA-Z0-9\-]+(\s*[a-zA-Z\-]+)*$/.test('aaaaaaa aaaaaaaaa aaaaaa aaa aa aa ');
console.log(performance.now() - start);
```
... you'll find it's also pretty slow in Chrome and Firefox; but not Safari. (It must have a different testing algorithm.) I think you're running into a problem called catastrophic backtracking. I don't know enough about regex evaluation but [this page](https://en.wikipedia.org/wiki/ReDoS) might help you figure out what's going on.

```javascript
/^[a-zA-Z0-9\-]+(\s*[a-zA-Z\-]+)*$/
//                 ^
```
Changing this asterisk to `+` seems to make the test much faster. I think the `(\s*[a-zA-Z\-]+)*` part is problematic since the set with `+` nested in the group with `*` could cause it to try every possible way to cluster the characters in a word, but the one space minimum might make the check for the word linear? That's just a guess though.

(I removed the brackets around the `\s` because they aren't necessary as it's a single character, but I don't think that's actually relevant to the issue.)

**Comment by robrez** [comment]
@bicknellr Thanks for the feedback (`catastrophic backtracking` sounds epic!).

Since opening the issue, I've ditched auto-validate + regex in favor of binding to `invalid` using a _::deep breath::_ property computed inside of a debounced function executed via a property observer. eg:

```
<paper-input value="{{val::input}}" invalid$="[[_validVal]]"/>
...
observers: [ '_valCheck(val)' ],
_valCheck: function(val) {
  this.debounce('valcheck', function() { 
    this._validVal = expensiveComputation(val); }.bind(this),
    125);
}
```

In terms of this specific regex, I could optimize performance by splitting the string and checking the last token for validity.. etc.  

I think it's fair to close this issue and label it as user error.
