### ISSUE TITLE
Caret misaligned with type="search"

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-input#196]
Chrome stable:

<img width="229" alt="screen shot 2015-10-01 at 6 30 33 pm" src="https://cloud.githubusercontent.com/assets/238208/10237729/a97e62f2-686a-11e5-937a-c05e882c6393.png">

**Comment by notwaldorf** [comment]
This should have been fixed in https://github.com/PolymerElements/paper-input/pull/182 -- are you using the latest?

**Comment by ebidel** [comment]
Yeppers. `  bower.json: "version": "1.0.15",`

**Comment by ebidel** [comment]
Staging is https://polymer10-samples-dot-cr-status.appspot.com/samples

**Comment by notwaldorf** [comment]
Ah right, sorry, misunderstood. With `type="search"` you need to use use placeholders and not the label. I had added this to the demo, but deleted it, since the demo isn't really a doc, but I did add an explicit call-out in the docs: https://github.com/PolymerElements/paper-input/blob/master/paper-input.html#L40

The problem is that `type="search"` has native styling (left padding on Chrome, different left padding on Safari, no padding at all on Firefox, see: https://twitter.com/notwaldorf/status/646778535697211394 for screenshots and sob) that we cannot control, so it's not clear where we should offset the label to so that it works everywhere.

Because the `placeholder` attribute is the native one, it gets correctly offset (but in Chrome, you'll see that it has a left padding). 

I don't have a better solution than this, but I'm open to suggestions.

**Comment by notwaldorf** [comment]
You can see where the weird left padding comes from in the demo too, after the autofill:
<img width="228" alt="screen shot 2015-10-01 at 8 19 12 pm" src="https://cloud.githubusercontent.com/assets/1369170/10238821/bb74375c-6879-11e5-97fe-ac80f5532eb7.png">

`type=search` is not great. :sob:

**Comment by ebidel** [comment]
`placeholder` aligns the caret nicely. Thanks. The only reason I'm using type="search", is for the nice lil "X" for mobile. I'll close this as it's not an issue anymore.

Thanks for adding the note in the docs. I guess that'll get picked up on the next catalog push.
