### ISSUE TITLE
add special password-input with password strength indicator?

### ISSUE THREAD

**Issue by jab** [PolymerElements/paper-input#242]
https://accounts.google.com/SignUp has an example (but there's tons of other [prior art](https://blogs.dropbox.com/tech/2012/04/zxcvbn-realistic-password-strength-estimation/):).

(Would there have been a better place to open this issue? Happy to migrate it if so.)

**Comment by notwaldorf** [comment]
Unfortunately, I don't think this is something we'd add as part of the `paper-input` (because I don't think we want to make official promises about password strength), but that's certainly interesting. You could add your custom password indicator as an indicator. (see how the char counter is implemented)

/cc @tjsavage

**Comment by tjsavage** [comment]
Yeah I think this is a super good idea for a custom element. Generally I think the best practice we're learning is to generally try to keep elements simpler and create more different elements for different features. Like @notwaldorf said, I don't think the paper-elements are the right place for an official promise around password strength, but this would be a great element to build in general.

**Comment by jab** [comment]
Makes sense, thanks. Happen to know any other repos that might be interested in this? Still new to the Polymer ecosystem and https://elements.polymer-project.org/ is all I know of right now.

**Comment by notwaldorf** [comment]
If you publish your element to bower or npm, and set it up correctly, then it will appear in https://customelements.io/ (see the bottom of the page for instructions to make sure it shows up)

**Comment by jab** [comment]
Good to know, thanks @notwaldorf! Worth linking to that site from polymer-project.org?

For anyone interested, the only relevant existing element I found on customelements.io is [this one](http://lechlm.github.io/pw-strength-meter/components/pw-strength-meter/). (Looks like it currently uses icons rather than a meter, doesn't document how it evaluates password strength, and from looking at the code, doesn't do a very sophisticated analysis (not even close to zxcvbn, but maybe it's good enough for some people).)

**Comment by MeTaNoV** [comment]
@jab http://metanov.github.io/gold-password-input/ I use `zxcvbn`! :)

**Comment by jab** [comment]
@MeTaNoV Nice! Looks like it's brand new, so no wonder it didn't come up when I searched https://customelements.io/search/password a couple weeks ago. Nice work! Look forward to giving it a try!

Question about the name: This is not an official Google-supported element, is it? Doesn't calling it "gold-password-input" imply ownership under https://elements.polymer-project.org/browse?package=gold-elements which could be confusing if it's a third-party element?

**Comment by MeTaNoV** [comment]
@jab A lot of people are using some kind of naming convention like `paper-foo` for paper-related element, and so on...
Since there was a `gold-email-input` element, I thought it would be nice to have such naming. If Google complains somehow, I will rename it! :)
Also, do not hesitate to give me some feedback. It is already working well, but I still have some fine tuning to do (related to Issues with current element dependencies and Polymer itself).
