### ISSUE TITLE
Adding required attribute when type="number" is like having alwaysFloatLabel set

### ISSUE THREAD

**Issue by ismail-s** [PolymerElements/paper-input#253]
## Steps to reproduce

1. Create a paper input element like so:

    ```<paper-input label="test" type="number" required></paper-input>```
1. View this in a webpage.

## Expected

![image](https://cloud.githubusercontent.com/assets/3778413/11189663/20a406e2-8c89-11e5-82e0-ce3eab8ba521.png)

## Actual

![image](https://cloud.githubusercontent.com/assets/3778413/11189678/33b595fc-8c89-11e5-9dc5-2511212fc0ef.png)

## Removing the required attribute:

    ```<paper-input label="test" type="number"></paper-input>```

stops this issue from occurring (ie that is the crucial part of this bug).

**Comment by notwaldorf** [comment]
This looks already fixed: http://jsbin.com/biqofiw/edit?html,output

**Comment by ismail-s** [comment]
Awesome.

**Comment by pieter-vincken-agilians** [comment]
It is only partially fixed? The label doesn't come down after making the input empty again? 

Steps to reproduce:
1. Enter a number
2. Remove the number
Result: Label keeps floating instead of coming back down (as type="String" does)

(Tested with the JSBin example of notwaldorf in Google Chrome 48.0.2564.97)
