### ISSUE TITLE
Unclear text in docs

### ISSUE THREAD

**Issue by zoechi** [PolymerElements/paper-input#260]
Several attributes have this text in the documentation 

> Bind this to the <input is="iron-input">'s xxxxx property.

I have no clue what this means. Do I have to to something, how? Is this what the element does itself?

**Comment by notwaldorf** [comment]
That is the documentation for the `PaperInputBehavior`, which is a behaviour that you could use to implement your own paper-input like thing. In the docs they show up because they're used by `paper-input`. You don't have to bind them, they're already bound for you by the element. I will try to make the docs clearer in this case
