### ISSUE TITLE
The character counter counts breaklines double character

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-input#271]
You can check it the [paper-input demo](https://elements.polymer-project.org/elements/paper-input?view=demo:demo).

**Comment by notwaldorf** [comment]
@abdonrd would you like to send a PR to fix this, by any chance? :)

**Comment by abdonrd** [comment]
@notwaldorf I start to research and I find [this comment](https://github.com/PolymerElements/paper-input/blob/master/test/paper-input-char-counter.html#L100-L101). I don't understand why. :confused:

**Comment by notwaldorf** [comment]
@abdonrd I think it's related to this: http://stackoverflow.com/questions/10030921/chrome-counts-characters-wrong-in-textarea-with-maxlength-attribute, where each new line is actually '\r\n'. This fix came from the 0.5 version of the element, but this issue may have been fixed in the lastest Chrome/Firefox, so we might not need this workaround anymore

**Comment by abdonrd** [comment]
@notwaldorf Yes, during the research I found several posts about it.

I propose this: https://github.com/PolymerElements/paper-input/pull/322/files

**Comment by abdonrd** [comment]
Close by https://github.com/PolymerElements/paper-input/pull/322! :tada:
