### ISSUE TITLE
No built-in dom-binding?

### ISSUE THREAD

**Issue by cpboyd** [PolymerElements/paper-input#319]
If I wrap the code in a dom-bind template, everything works as expected:
```html
<template is='dom-bind'>
  <input type='hidden' name='test' value='[[selected]]'>
  <paper-input-container attr-for-value='selected'><label>Test</label>
    <paper-tabs class='paper-input-input' selected='{{selected}}'>
      <paper-tab>Tab 1</paper-tab>
      <paper-tab>Tab 2</paper-tab>
      <paper-tab>Tab 3</paper-tab>
    </paper-tabs>
  </paper-input-container>
</template>
```

My question is: Aren't Polymer elements supposed to have built-in dom-binding?

If I, instead, try something like the following (by removing template and putting the hidden input inside of paper-input-container), the dom-binding never occurs:
```html
  <paper-input-container attr-for-value='selected'><label>Test</label>
    <paper-tabs class='paper-input-input' selected='{{selected}}'>
      <paper-tab>Tab 1</paper-tab>
      <paper-tab>Tab 2</paper-tab>
      <paper-tab>Tab 3</paper-tab>
    </paper-tabs>
    <input type='hidden' name='test' value='[[selected]]'>
  </paper-input-container>
```

**Comment by notwaldorf** [comment]
Your code would work if it was *inside* another custom element. Inside a `<dom-module>` definition, binding works as you expect it, because Polymer is managing it. However, in the plain HTML world, you have to somehow tell Polymer to manage these bindings, and that's what `template is="dom-bind"` does. Here's the docs for more details: https://www.polymer-project.org/1.0/docs/devguide/templates.html#dom-bind
