### ISSUE TITLE
Getting the textarea to scroll by setting an explicit height.

### ISSUE THREAD

**Issue by JockeCK** [PolymerElements/paper-input#320]
In the documentation for iron-autogrow-textarea it says you can get the scrollbar to appear by either setting explicit height or using the property maxRows. 

Is it possible to do either in the paper-area element as well?

**Comment by notwaldorf** [comment]
Here's a jsbin for that: http://jsbin.com/ziqele/edit?html,output. I had to add an `overflow:hidden` as well, since the textarea seems to be growing crazy without it. I think this is a bug in `iron-autogrow-textarea`, though, so I'll re-open it in that repo.

Please let me know if this doesn't work for you!
