### ISSUE TITLE
Support HTML 5 date, time type attributes

### ISSUE THREAD

**Issue by jasmith79** [PolymerElements/paper-input#325]
Currently according to the catalog page the types of inputs supported are text, number, and password. Although not officially supported for ```paper-input``` elements, in current stable chrome and edge the date and time types on inputs are handled appropriately but not in firefox, safari, or IE 10+.

A fair number of developers will be concerned with standardizing the UX across platforms (necessitating custom interfaces). But it would be particularly nice for mobile platforms to not *have* to ship a custom date/time picker over the wire; to instead have the option to use ones provided by the browser. Chrome on android in particular does a really nice job of this, but others are perfectly serviceable.

**Comment by notwaldorf** [comment]
That's because the native `<input type=date>` is only implemented by Chrome (and apparently Edge?), but not in FF, Safari or IE: http://caniuse.com/#search=date

For the browsers where it's implemented, it _can_ be used in `paper-input`, just like you would with the native input: http://jsbin.com/xiwobe/edit?html,output. Here's a screenshot of what that looks like in Chrome:
<img width="301" alt="screen shot 2016-02-02 at 10 05 16 am" src="https://cloud.githubusercontent.com/assets/1369170/12759149/7e11ad78-c994-11e5-85b1-955704d5d22d.png">

Closing, since this is the classic "platform has not implemented this feature" shenanigans :)
