### ISSUE TITLE
When trying to focus an input as a result of a selection action, the keyboard dissapears on android mobile.

### ISSUE THREAD

**Issue by notwaldorf** [PolymerElements/paper-input#336]
_From @simonabutnaru on February 12, 2016 14:58_

I could reproduce this issue on jsfiddle using google nexus 5. On iphone 6, the input doesn't even show. On desktop, it works fine.
https://jsfiddle.net/simona_butnaru/xt9oxg66/ 

I think the problem is the blur event that is triggered when an item is selected from paper-menu-button.

_Copied from original issue: Polymer/paper-input#197_

**Comment by notwaldorf** [comment]
@simonabutnaru (moved the issue to the right repo)

So, here's the thing about focus and blur events with `paper-input`: when you focus the `paper-input`, it has to focus its native `<input>` child (because that's what you're typing into), which will then fire a `blur` event on the host `paper-input`. This means that if you expect to get exactly one `blur` event and only get it when you tab away from the `paper-input`, you'll be wrong.

If I comment out the code inside the `inputBlurHandler`, then the input shows up fine for me.

Does this kind of make sense and/or help?

**Comment by simonabutnaru** [comment]
@notwaldorf I understand what you're saying. For the moment we gave up listening blur event on input, but we still have an issue with the keyboard. When focusing the input, the keyboard does not have enough time to open, because of the blur event. 
If we call focus event with 100ms delay, everything works fine. But I don't find this as a good solution.

**Comment by notwaldorf** [comment]
I think there might be a problem in your setup :(
Here's a very basic JSBin which just focuses an input when a button is clicked: http://output.jsbin.com/nuqizi

I've tested this on both iOS and Android, and the keyboard shows up fine. Is there something else you're doing to maybe trigger a blur event?

**Comment by simonabutnaru** [comment]
I think you misunderstood what the cause of this issue is. From the beggining, I said that "I think the problem is the blur event that is triggered when an item is selected from paper-menu-button". By this, I was trying to say that, when selecting an item from paper-menu-button, a blur event is triggered and because of that the keyboard gets closed.

The JSbin you made, works for me too. Try to replace the button with paper-menu-button, an see if you get my problem.

Here I made a movie where you can see what is happening.
[issue-blur.zip](https://github.com/PolymerElements/paper-input/files/134476/issue-blur.zip)

**Comment by notwaldorf** [comment]
Sorry, I misunderstood that there was a problem with `paper-input`, because that's where the issue was filed :) My bad!

Yes, you are completely right: after you click the item, it has to close the dropdown, so it will steal whatever focus it applied. Just tested this (http://jsbin.com/gofutum/edit?html) on android and it works fine: basically i moved the focus to an `iron-overlay-closed` handler, which is fired after the menu is closed.

Does this work for you?

**Comment by simonabutnaru** [comment]
It worked with your idea, Monica. Thanks a lot :)
You can close the ticket now:)

**Comment by notwaldorf** [comment]
Sweet! Good to hear 🎉
