### ISSUE TITLE
Invalid attribute doesn't get updated as wanted on paper-inputs values changes

### ISSUE THREAD

**Issue by fakiolinho** [PolymerElements/paper-input#346]
I have a simple login form with `auto-validate` in my inputs. This is a typical one:
```html
<paper-input id="username" name="username" type="text" value="{{user.username}}" label="Username" error-message="Please enter your username" auto-validate required></paper-input>
```
I watch with an observer for their 2-way notifications and then i check if the inputs are invalid with `this.$.myInputID.invalid;`.

```javascript
observers: [
    '_inputsChanged(user.*)'
],
_inputsChanged: function(user) {
    console.log('Username is invalid: ' + this.$.username.invalid);
    console.log('Username value: ' + this.$.username.value);
}
```

The issue is this. I am getting strange and quite inconsistent results. I don't try to manipulate `invalid` attributes. I just want to track for invalid fields and run a generic validation for my form. For example for a required field if i type one char, i am getting it is invalid but it really has some value as expected. When i add another char then it becomes valid.
![screenshot at feb 23 16-48-21](https://cloud.githubusercontent.com/assets/2962687/13255429/cf7db628-da4e-11e5-850a-e71ab937f265.png)

In the documentation for `paper-input` a warning is made for `invalid` use together with `auto-validate` but it advices against manual managing not for simple tracking. My demo code can be checked [here](http://jsbin.com/xazogit/10/edit?html,output).

**Comment by notwaldorf** [comment]
I think that you're checking too soon. I updated the code (http://jsbin.com/fefapo/2/edit?html,console,output) to basically wait a tick before checking `invalid` and I think now it makes sense.

What's happening is that when the `value` is changed, the observer gets fired, and _then_, as a response to this observer firing, the `paper-input-container` validates it: https://github.com/PolymerElements/paper-input/blob/master/paper-input-container.html#L503

Since you were also doing your logging in an observer, you were basically checking at the same time `invalid` was being computed (and probably too early).

Let me know if this doesn't work for you and we can re-open this!
