### ISSUE TITLE
type="date" not working on Safari/iPad

### ISSUE THREAD

**Issue by brOOper** [PolymerElements/paper-input#352]
There is an issue on iPad's Safari with `<paper-input type="date" />`. It is only touchable if there is an initial value set. If there is no value or the value gets deleted the field is no longer touchable. Same for `<paper-input type="time" />`.

Browser: Mozilla/5.0 (iPad; CPU OS 9_2_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13D15 Safari/601.1

``` html
<paper-input type="date" label="no value (does not work)" />
<paper-input type="date" label="initial value (does work)" value="2016-03-03" />
```

https://plnkr.co/f5gzvmotEkEJ6zM5atsN

**Comment by 43081j** [comment]
As far as I can see, the docs seem to imply this isn't yet supported (see [here](https://elements.polymer-project.org/elements/paper-input), `The supported types are text, number and password.`).

Which would make sense, seeing as the placeholders and native date contents conflict in chrome too ([here](http://i.imgur.com/q90IPpJ.png)).

**Comment by notwaldorf** [comment]
Yup, that looks like a bug. Here's a repro JSBin: http://jsbin.com/runurip/edit?html,output

**Comment by capira12** [comment]
+1

**Comment by aarondrabeck** [comment]
+1

**Comment by kaseyhinton** [comment]
+1

**Comment by BorntraegerMarc** [comment]
whats happening with this issue? It's still not fixed...

**Comment by shawncplus** [comment]
Just ran into this on polymer version 1.9.1 though for `type="time"` instead of date. A raw `input is="iron-input" type="time"` works just fine so `paper-input` is definitely the culprit. Can't check to see if this is fixed in later versions atm. @BorntraegerMarc what version of Polymer were you on?

**Comment by BorntraegerMarc** [comment]
@shawncplus I was on polymer 2.0.1

**Comment by shawncplus** [comment]
So I have found a workaround. Apply any styles to it that will give the `input` element a height. So a border or anything really.

```
  .my-input {
    --paper-input-container-input: {
      min-height: 1px;
    };
  }
```
If I had to take a wild guess at why this work I'd say it's because:

* paper-input-container sets the padding to 0 and removes the border, this sets the inputs initial height to 0
* webkit, seeing the element has no height does not force the element to layout
* because the element doesn't layout focusing it ignored
* because it doesn't receive focus the OS controls aren't shown
* Setting an initial value works because the input has content so has a height

Therefor the solution of setting a min-height on the input itself always causes it to layout

@BorntraegerMarc ^

**Comment by d4l3k** [comment]
This doesn't seem to be fixed. I'm still seeing this issue under 2.0.3.

http://jsbin.com/runurip/edit?html,output

**Comment by d4l3k** [comment]
Just confirmed, it's still a bug in `2.0.3` despite that recent pull request.

This still fixes it:
```
--paper-input-container-input: {
      min-height: 1px;
    };
```

**Comment by shawncplus** [comment]
@d4l3k yeah that's because I'm a big dummy and my PR was bad and had the `min-height` applied to the wrong class. I'll send in a fixed PR :/

**Comment by Michaelwan777** [comment]
It doesn't work in my mac book pro as well. That html is normal input type="date". It displays as type="text". Is this bug still here till today?

**Comment by jhongmez** [comment]
El error aun persiste, no he encontrado como darle solución a esto
