### ISSUE TITLE
Typing 'e' writes on top of label

### ISSUE THREAD

**Issue by samuelli** [PolymerElements/paper-input#377]
### Description
'eee' writes on top of the label
![result](http://i.imgur.com/hjkiRA8.png)

### Expected outcome
Label floats

### Actual outcome
Label stays

### Live Demo
http://jsbin.com/kasivaxuni/edit?html,output

### Steps to reproduce
1. Type 'eee' into the paper-input type='number' field

**Comment by notwaldorf** [comment]
We seem to get no `input` event fired when the first `e` is typed :(

**Comment by notwaldorf** [comment]
@samuelli I'm tempted to close this since I don't really see how we can fix it; `<input type=number>` does everything in its power to not save the invalid value anywhere, so without doing enormous hacks (saving the entered text after `iron-input`'s  `_onKeypress` and checking it in `_onInput`, and hope for the best these are always in the same order) I don't see a solution.
WDYT?

**Comment by samuelli** [comment]
Yeah, that's probably fair!
