### ISSUE TITLE
auto-validate doesn't work on element registration/instantiation

### ISSUE THREAD

**Issue by nicholaswmin** [PolymerElements/paper-input#381]
### Steps to reproduce

- Dynamically create some `<paper-input>` elements with `auto-validate` & `required` within a `<template is="dom-repeat">`
- Populate some of the `<paper-input>`'s with `null` `values`.

### Expected behaviour

- Expected the error message of a `<paper-input>` with `auto-validate` & `required` to appear on *instantiation* (for lack of a better word) of that element.
- As it seems the elements needs to be blurred before the validation runs.

### Code Example 

- Heres a [JSFiddle](https://jsfiddle.net/2q3fqehz/31/) example.
- The 2nd `<paper-input>` has `null` value and I was expecting this to have it's error message displayed  when that it was *dom-repeated*, not only after the user has focused and then blurred out of it.

Is this a bug or is this by design?

**Comment by notwaldorf** [comment]
I think this is working as intended (introduced here: https://github.com/PolymerElements/paper-input/pull/148). Basically, imagine if you have a form that has all fields required. It's weird to start by marking all the fields red (and invalid), since the user has not gone around to actually interacting with them; this is why we explicitly only validate after the input changes, or after it is blurred.

**Comment by nicholaswmin** [comment]
Makes sense but there are times when auto-validation would be very useful if it happen on `attached` instead. I've stumbled across a case like this (creating a new row of fields that needs filling-in) - isn't there any way we can have a custom prop to set that?

Something along the lines of `auto-validate-on-attach` perhaps?

**Comment by notwaldorf** [comment]
@nicholaswmin You can just call `validate()` manually (especially if you're doing the attaching), which will set the `invalid` attribute for you: http://jsbin.com/kelako/edit?html,output
