### ISSUE TITLE
type=number disable pattern & minlength

### ISSUE THREAD

**Issue by lp177** [PolymerElements/paper-input#391]
### Description

When I set the paper-input to type number on the last version (1.1.11) the pattern and minlength attributes seem to be totally ignored, breaking the ability to validate/auto-validate this input likewise than without type.

### Expected outcome

That seem to be a bad choice of type to take a type number and wanted also use a pattern, but the aptitude of this type to open numerical keyboard with this attribute value grow him utility outdoor her design.

### Actual outcome

Actually I can force this behavior in add attribute onkeyup="this.set( 'invalid', ( String(this.value).match(this.pattern) ) ? false : true)" but it's a choice, bug or an mistake of my part ?

### Simulation of this bug

[Demo](https://jsbin.com/cupugav/edit?html,output)

**Comment by notwaldorf** [comment]
Please provide a JSBin containing a set of reproducible steps. Check this element's CONTRIBUTING.md for an example.

**Comment by lp177** [comment]
Welcom, Queen of emojis, sorry for this miss, I thought it was too basic for do a demo, but it's a pleasure to do that: [demo](https://jsbin.com/cupugav/edit?html,output)

Thanks for your read.

**Comment by notwaldorf** [comment]
This is a behaviour of the native input, on which `paper-input` relies: 
- `<input>` demo: http://jsbin.com/fevaso/edit?html,output
- `<input type=number>` internally validates its value and sets the validity to `valid` iff the value can be converted to a floating point number: https://www.w3.org/TR/html5/forms.html#number-state-(type=number). 
- the `pattern` attribute (which is a native attribute, not a `paper-input` specific one) only applies to `text, search, tel, url, email or password` (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-pattern), otherwise its ignored.

If you want a numeric keyboard, you can set the type to `tel` instead, which won't restrict you to typing letters on desktop, but will pop up the telephone keyboard on mobile: https://jsbin.com/kejuxe/edit?html,output.

Closing, as this is how `input type="number"` works.

**Comment by lp177** [comment]
Thanks for your complete answer.
