### ISSUE TITLE
Remove typography.html import

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-input#412]
### Description

With the typography.html, loads Roboto font.
[PolymerElements/paper-input/paper-input-error.html#L13](https://github.com/PolymerElements/paper-input/blob/master/paper-input-error.html#L13)
[PolymerElements/paper-input/paper-input-char-counter.html#L12](https://github.com/PolymerElements/paper-input/blob/master/paper-input-char-counter.html#L12)
### Expected outcome

Not load Roboto font, like other elements.
Example: https://github.com/PolymerElements/paper-toast/pull/58
### Actual outcome

Loads Roboto font.

**Comment by notwaldorf** [comment]
This is a breaking change, and wil be addressed in the 2.0 release

**Comment by abdonrd** [comment]
Another option is remove the `roboto.html` import in the [typography.html#L12](https://github.com/PolymerElements/paper-styles/blob/master/typography.html#L12).
And the user import the `roboto.html` if he wants.

@notwaldorf, WDYT?

**Comment by notwaldorf** [comment]
That is also a breaking change.

We have already planned to deal with the Roboto font issues for all the elements, in the 2.0 release (we will remove the `typography.html` import but leave the mixins, so that importing the file in the app (or defining `--font-common-base` or whatever it's called) will bring the Roboto font if needed

**Comment by abdonrd** [comment]
Thanks @notwaldorf!

**Comment by osamamaruf** [comment]
Any update on this?

**Comment by abdonrd** [comment]
As far as I know, the Polymer Elements are not going to continue developing. So I close this issue.
