### ISSUE TITLE
Clarify documentation

### ISSUE THREAD

**Issue by phidias51** [PolymerElements/paper-input#420]
There are a lot of attribute comments that say "If you're using PaperInputBehavior to implement your own paper-input-like element...". This isn't very helpful.  For example, you have an **autocomplete** attribute.  What is it for? Does paper-input support autocomplete? If so, can you show an example of how to do it?

Comments about using PaperInputBehavior, should be in PaperInputBehavior, or in a separate guide.

**Comment by notwaldorf** [comment]
Unfortunately, those comments come from `PaperInputBehavior` (https://github.com/PolymerElements/paper-input/blob/master/paper-input-behavior.html#L201), because `paper-input` implements that behavior.

This means that `paper-input` has this attribute, and you can use it as you would on a native `<input>` element: `<paper-input type="email" autocomplete="on">`

**Comment by phidias51** [comment]
I think it would be clearer if the comments for each attribute described the attribute and the comments about implementing PaperInputBehavior were separated.

**Comment by notwaldorf** [comment]
That's good feedback for the catalog (since right now it just aggregates all the properties inherited from the behaviour, so it's unable to separate them)

/cc @justinfagnani

**Comment by phidias51** [comment]
You might also just modify the doc so that the first line of the doc indicates what the field is for, and the subsequent lines contains the details needed to implement the PaperInputBehavior.

/cc @justinfagnani
