### ISSUE TITLE
Event oninput on work when  window.Polymer pre-defined

### ISSUE THREAD

**Issue by Gaubee** [PolymerElements/paper-input#438]
### Description

My code:

```
<head> <script>
    window.Polymer = {
      dom: 'shadow',
      lazyRegister: false
    };
  </script>
......
<p>long_url:{{long_url}}</p>
<paper-input value="{{long_url::input}}" label="BUG?"></paper-input>
```

I'm using v1.1.17~v1.1.18;
`{{long_url::input}}` no work. but `{{long_url::change}}` work fine.
### Expected outcome

`long_url` should changed on inputed;
### Actual outcome

`long_url` will no change.
### Live Demo

Example:  https://jsbin.com/gegogiwidi/1/edit?html,output
### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
Hmm, so adding a listener to the `input` event works: http://jsbin.com/pacatuw/edit?html,console,output

@azakus -- do you know why this might happen?

**Comment by azakus** [comment]
You can only use that syntax if the origin of the event is the node with the binding syntax.

Here's an example:
```html
<div foo="{{value2::input}}">
  <input value="{{value::input}}">
</div>
```

`value` will get updated because the `<input>` is the origin for the `input` event.
However, `value2` does not get updated because `input` event did not originate on `<div>`

FWIW @Gaubee, you can just use `value="{{long_url}}"` in your example because `<paper-input>` cooperates with databinding: https://jsbin.com/raqesuk/edit?html,output

**Comment by Gaubee** [comment]
Wa... This issues opend 9/11/16, I'm no longer using Polymer now.
