### ISSUE TITLE
Paper-input leaking text styles?

### ISSUE THREAD

**Issue by fafcrumb** [PolymerElements/paper-input#442]
### Description

Importing paper-input seems to leak text font styles to the rest of the page. What I have in the demo below is a vanilla polymer starter kit 2 with paper-input imported in view1. First I switch to that view (loading paper-input) which changes the text, then I hard refresh (creating the same effect). The effect is even more jarring in firefox.

### Expected outcome

Importing paper-input does not change outside styles.

### Actual outcome

Importing paper-input universally changes text font/size.

### Live Demo

![paper-input-demo](https://cloud.githubusercontent.com/assets/17421035/18621852/cfb50000-7df6-11e6-8263-fc4b5dacdf4c.gif)

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
Importing `paper-input` also imports `typography.html`, which defines a whole bunch of mixins that maybe have been used, but not defined before in elements. To get around the style flash, I recommend importing `paper-styles/typography.html` in the root of your application.

Removing this dependency is being tracked in https://github.com/PolymerElements/paper-input/issues/412, so I'll close this issue since there's nothing else we can do :(
