### ISSUE TITLE
How to disable underline in paper-input element?

### ISSUE THREAD

**Issue by abhilash29** [PolymerElements/paper-input#459]
`no-label-float` does work, however, I would like to furthermore disable the underline in paper-input. How can I achieve this?

**Comment by robrez** [comment]
You might be able to just use 'placeholder' instead of label. `no-label-float` works for me over at the demo page:
https://elements.polymer-project.org/elements/paper-input?view=demo:demo/index.html&active=paper-input
_look to the "The label can have different floating states" section._

You can get rid of the underline by using the style mixins:
```
<style is="custom-style">
  :root {
    --paper-input-container-underline: {
      display: none;
    };
    --paper-input-container-underline-focus: {
      display: none;
    };
    --paper-input-container-underline-disabled: {
      display: none;
    };
  }
</style>
```

**Comment by notwaldorf** [comment]
Yup, @robrez's solution is right. You don't need do disable the label or anything. Here's a JSBin with an example: http://jsbin.com/waginob/edit?html,output

**Comment by vegegoku** [comment]
@notwaldorf that JSBin shows that the solution suggested does not work
