### ISSUE TITLE
how to get browser to save and autocomplete username/passwords?

### ISSUE THREAD

**Issue by davidmaxwaterman** [PolymerElements/paper-input#462]
### Description
I have a couple of paper-input elements, one username and one password. The username is type="text" and password is type="password". I have a paper-button with an on-tap handler to attempt the log in.
I am trying and failing to get the browser to remember the username/password combo in its password manager.

### Expected outcome
When the paper-button is tapped, the browser offers to remember the username/password for the site.

### Actual outcome
Browser does not offer to remember the username/password for the site.

### Steps to reproduce

1. Put two `paper-input` elements on the page, one with type="text" and one with type="password" and a paper-button
2. Open the page in a web browser.
3. tab the paper-button

obviously, it doesn't do anything, but I'm looking for a way to trigger chrome's password manager to save the username and password. There's a password demo example in the docs, but no mention of making this happen. I've tried setting autocomplete to 'username' and 'current-password' appropriately, but they make no difference.

### Browsers Affected
I'm only trying chrome 54 at this point, but I'm looking for the general solution for using paper-input for username/password.

**Comment by notwaldorf** [comment]
So, there's a couple of things that contribute to autocompletion: the `name` and 'autocomplete' attributes, and the element living in a form. Here's a JSBin with an example: http://jsbin.com/fafebur/edit?html,output. Since other autocompletes work, I'd be very surprised if `paper-input` breaks _just_ for an input. Unfortunately that example doesn't work, and I can't test whether the password actually works, because it's on JSBin and it doesn't actually submit the form on a real domain (and so Chrome doesn't prompt the password manager).

There's a couple of things I would try:
- replace the `paper-input` with a native `<input>`. If that doesn't work either, then you have a different problem, and it's not paper-input related. Unfortunately, that sounds like a generic form issue, so googling is your best bet there :)
- if the `input` element autocompletes but the `paper-input` doesn't, please re-open the issue, since that would be a `paper-input` issue.

Sorry I can't be of more help :(

Closing, since this looks like it's a generic `input` and `form` issue, and not a `paper-input` one

**Comment by mrdevin** [comment]
I am having the same problem in a Polymer 2.0 app
![autocomplete](https://user-images.githubusercontent.com/864287/29334788-e5d69526-8208-11e7-8631-9ba4de6db202.gif)

**Comment by davidmaxwaterman** [comment]
I tried lots of things, but couldn't get anything to work. A known working example/technique would be great. Someone suggested it isn't working due to shadow dom, but I tried putting it in <body> and triggering it from a button handler inside a polymer element, and that didn't get any success either.
I wonder if this mechanism doesn't work for localhost:8081, and/or it *has* to have a server-side script to handle the submit (I've been trying to use onSubmit="return false;" to avoid that).
@notwaldorf any suggestion?

**Comment by davidmaxwaterman** [comment]
chrome is broken for <input>s inside shadow dom:
https://bugs.chromium.org/p/chromium/issues/detail?id=746593

I have had some modicum of success using <input> in the top level document, and copying back and forth the `value`s.

The problems that remain are:

1. while the username input copies just fine when the password manager fills it in, the password input doesn't copy until I click on the document.
2. if you log out and back in again as a different user, it seems to remember the password for the previous log in.
3. it's *very* difficult to remove the passwords from the password manager - in some cases, it seems to add them back in again all on its own.

I made a reduced test case (since my app is closed source), but it isn't so great since I struggle to make it *offer* to remember the credentials - it does show the key icon in the URL bar though, which tells me that it is recognising the inputs. I hope someone might be able to improve on it - please let me know any way to make it work in an acceptable way:

https://github.com/davidmaxwaterman/paper-input-password-manager

**Comment by JosefJezek** [comment]
Alternative solution is use Credential Management API...

https://github.com/GoogleChromeLabs/credential-management-sample

**Comment by sebs** [comment]
Since I am wrestling with this? Why is it closed? There is neither a solution in this thread, not a fix supplied. If there is a obvious solution, please document it.

**Comment by andersforsell** [comment]
I am also looking for a solution to this, @sebs : did you find one?

**Comment by sebs** [comment]
Yeah ... kinda experimental ... use the chrome credentials api. Which is still highly experimental, even on firefox i got problems
