### ISSUE TITLE
On Input Event

### ISSUE THREAD

**Issue by douglasrlee** [PolymerElements/paper-input#498]
### Description
Can we get an `oninput` attribute added to the input tag? 

Doing so would allow us to debounce the validation. 

OR you could add a `debounce` attribute to allow us to debounce the `auto-validation`.

**Comment by notwaldorf** [comment]
The `input` event already fires, in both shady and shadow DOM: http://jsbin.com/pacatuw/edit?html,console,output (you can comment out the `Polymer = {dom: "shadow"};` line if you want to test shady DOM), so all you need to add is an event listener.

If you want the short hand for `oninput` that automatically sets that event listener, I don't think that's a feature we should add, since most custom elements don't behave that way.

Closing this, as I think what you need is already there, but let me know if that doesn't work out for you
