### ISSUE TITLE
[Feature request] Add support for helper text

### ISSUE THREAD

**Issue by alejost848** [PolymerElements/paper-input#522]
![Helper text](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B5ZSepuCX1xOLXF0MEpld2h6YjQ/placeholder_helper.png)
*Helper text can support placeholder text in guiding the user.*

### Feature request
I find it odd that this hasn't been requested before, but now that the April 2017 update of the Material Design specs is out, and the use of helper text in text fields [is better documented](https://material.io/guidelines/components/text-fields.html#text-fields-layout), it would be great if we could have a new property in `paper-input` called `helperText`, similar to `errorMessage`, that receives a string and displays it below the input. 

According to the specs:

* Helper text gives context about a field’s input, such as how the input will be used.
* It should be visible either persistently or only on focus [(as seen in this video from the previous specs)](https://storage.googleapis.com/material-design/publish/material_v_10/assets/0B7WCemMG6e0VcHFla0dwOE5pVVE/forms-supportive-content-v3_xhdpi.webm)
* When an error message is displayed and until it is fixed, the error replaces the helper text. [(See the different states possible)](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B5ZSepuCX1xOb195LU9KWEdIeEk/states.png)

I consider this is a really useful feature that can improve an already great element.

**Comment by cordovapolymer** [comment]
Bump! Been looking how to implement Helper text today and found have this request. It's definitely required in paper-input.

**Comment by dantman** [comment]
paper-input-container already has add-on text for the error message / char counter, and the error message styling is not part of that (error styling is a separate component). So it shouldn't be hard to add helper text.

**Comment by notwaldorf** [comment]
Yup, as @dantman mentioned, you should create an add-on and add it to `paper-input-container` directly. I don't think this is something we want to add to `paper-input`, since that element is quite big enough as it is.

**Comment by dantman** [comment]
Why shouldn't it? I meant it shouldn't be hard to add helper text to PolymerElements/paper-input. It should be relatively trivial, as all that is needed is another dom-if, a paper-input-helper style, and a `<paper-input-helper slot="add-on">[[helperText]]</paper-input-helper>`. It is **not** easy for users of paper-input to add helper text.

paper-input does a bunch of things, including passing on the right properties to the right element (whether iron-input or paper-input-container), implicitly handling alwaysFloatText for some types, and applying various key input styles.

For paper-input to implement helper text, it's a few lines of code implementing a standard part of Material Design. For a user of paper-input to add helper text, it's a matter of practically re-implementing part of paper-input.

**Comment by notwaldorf** [comment]
`paper-input` is already a very expensive element -- the more we add to it, the more unperformant it will be, which is why we're currently not adding any new features to it. 

In particular, this can be easily done with just html/css, since the helper text isn't tied to the focused/floated/error etc state of the input: http://jsbin.com/pulewul/edit?html,output. You can wrap this in a custom element decorator if you want, but I do not think this feature is valuable enough to add it to an already very expensive element.

**Comment by dantman** [comment]
@notwaldorf No, proper helper text can **not** be added with just html/css, helper text **is** tied to the state of the input.

https://material.io/guidelines/components/text-fields.html#text-fields-layout

> #### Error message
> When input isn’t accepted, text fields can display an error message below the input line, with instructions on how to fix the error. **Until the error is fixed, the error replaces the helper text.**

Helper text is part of the official material guidelines for text fields which paper-input is based off of. It's a feature liable to be used in just about any normal form (there is nothing strange about having both hint text and validation for a form field). The code to add it to paper-input is minimal and should not significantly affect performance. It is tied to the state of paper-input. And the extra work to paper-input users (add boilerplate to each input, style hint text, tie it to the validation state of the input) instead of just using `helper-text="foo"`, is significant.

There is seriously no good reason to intentionally exclude this part of material design from paper-input.

**Comment by christophe-g** [comment]
@notwaldorf - can this be re-opened/re-discussed. 

Understand the performance issue, but would be nice to follow the material specs on this matter.
