### ISSUE TITLE
Failed to execute 'setAttribute' on 'Element': 'class\' is not a valid attribute name.

### ISSUE THREAD

**Issue by Papuk34** [PolymerElements/paper-input#612]
Im gettting the above error message. 
I use the following dependencies:
```  
"dependencies": {
    "@polymer/font-roboto": "3.0.0-pre.1",
    "@polymer/paper-input": "3.0.0-pre.4",
    "@polymer/polymer": "3.0.0-pre.4",
    "@webcomponents/webcomponentsjs": "1.1.0"
  },
```
I import the element like this
`import * as PaperInput from '../../../node_modules/@polymer/paper-input/paper-input.js';`

And use it like this
`<paper-input value="{{jobDbId}}"></paper-input>`

I found attributes named "class\\$" (paper-input-container.js) and "aria-live\\$" (iron-a11y-announcer.js) which causes the error.
When i remove the \ everything works fine.

Am I doing something wrong with the dependencies?

**Comment by klauskobald** [comment]
I have the same problem !

**Comment by notwaldorf** [comment]
cc @FredKSchott @usergenic

**Comment by FredKSchott** [comment]
Thanks for filing! This is a known issue. Since we're converting all of our elements automatically, this is actually an issue that needs to be fixed in the modulizer itself.

You can track our progress (and get involved!) here: https://github.com/Polymer/polymer-modulizer/blob/master/docs/polymer-3-element-status.md
