### ISSUE TITLE
Unable to style paper input focus

### ISSUE THREAD

**Issue by Pixelsnbeards** [PolymerElements/paper-input#638]
### Description

I want to style paper input by changing the focus underline to a full box border with a dropshadow. I can't seem to find out which mixin is supposed to change the underline to a full box border.  Tried all mixins from paper-input-container with no succes.

### Expected outcome

On focus give the paper input a full border. (see screenshot)

![screen shot 2018-03-26 at 14 09 12](https://user-images.githubusercontent.com/31650718/37905608-aef9b488-30ff-11e8-95b3-ee7c43baf7aa.png)

### Actual outcome

Only underline is visible, able to change its colour and state (solid, etc)

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by notwaldorf** [comment]
Ah hmm, that seems to have broken in the 2.x port because of this line: https://github.com/PolymerElements/paper-input/blob/master/paper-input-container.html#L309
(we distribute the `iron-input`, not the `input` itself). I wonder if adding the `paper-input-input` class [here](https://github.com/PolymerElements/paper-input/blob/master/paper-input.html#L231) would fix this?

**Comment by Pixelsnbeards** [comment]
Adding ::slotted(iron-input) has fixed the problem, but it's not sustainable without updating the source code. Please add this in the next fix.
