### ISSUE TITLE
The package.json has no main field

### ISSUE THREAD

**Issue by lastmjs** [PolymerElements/paper-input#651]
### Description

The `package.json` does not have a `main` field, breaking bare specifiers because node module resolution depends on the main field.

### Expected outcome

Importing the element through a bare specifier should work: `import '@polymer/paper-input';`

### Actual outcome

With my tools, Zwitterion, I get: `Error: unknown: Cannot find module '@polymer/paper-input' from './text-editor-tools/prendus-multiple-choice-tool.ts'`

**Comment by notwaldorf** [comment]
cc @e111077

**Comment by e111077** [comment]
Hello this is due to multiple `main` files being listed in our `bower.json`. This is required for our modulizer to crawl the dependency tree and modulize multiple files. Some of our packages simply will not have a `package.json` `main` field until we can determine a canonical solution to what should go in this field for these types of packages.
