### ISSUE TITLE
Label overlaps input if value defaulted with binding

### ISSUE THREAD

**Issue by techniq** [PolymerElements/paper-input#97]
If the `<input>`'s value within a `<paper-input-container>` is data bound, the label does not properly float out of the way until the value changes
```html
<paper-input-container>
    <label>Works</label>
    <input is="iron-input" value="Default value" 
</paper-input-container>

<paper-input-container>
  <label>Broken</label>
  <input is="iron-input" value="{{ someValue }}">
</paper-input-container>
```

Here's an example showing the bug: http://codepen.io/techniq/pen/QbqJyr?editors=100

**Comment by notwaldorf** [comment]
@techniq You need to use `<input is="iron-input" bind-value="{{ someValue }}">`. From the [docs](https://github.com/PolymerElements/iron-input/blob/master/iron-input.html#L22), `value` will only notify when it changes because of user input (i.e. typing). If you care to be notified about imperative changes, like bindings, you need to use `bind-value`.

/cc @morethanreal in case I am wrong

**Comment by techniq** [comment]
@notwaldorf That did the trick.  I saw mention of it in the docs but didn't comprehend what it truly meant. :)
